import turtle
from turtle import *
turtle.speed(3)
#bgcolor("black")
def chakra():
    for i in range (1,25):
       color("blue")
       forward(50)
       backward(50)
       left(360//24)

def rectangle():
    color("orange")
    begin_fill()
    forward(300)
    left(90)
    forward(100)
    left(90)
    forward(600)
    left(90)
    forward(100)
    left(90)
    forward(300)
    end_fill()
    color("white")
    forward(300)
    right(90)
    forward(100)
    begin_fill()
    color("green")
    right(90)
    forward(600)
    left(90)
    forward(100)
    left(90)
    forward(600)
    left(90)
    forward(100)
    left(90)
    forward(600)
    back(300)
    left(180)
    end_fill()
    color("blue")
    circle(50)
    left(90)
    forward(50)
rectangle()
chakra()
turtle.hideturtle()
turtle.done()
